version: '3.1'

services: 
    php:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
           - 80:80
        volumes: 
           - ./Code:/home/ron/WebDevSapir/

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ron
        
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080